# Generated by Django 5.1.7 on 2025-03-13 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Generaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('nivel', models.CharField(choices=[('preescolar', 'Preescolar'), ('primaria', 'Primaria'), ('secundaria', 'Secundaria'), ('bachillerato', 'Bachillerato'), ('universidad', 'Universidad'), ('maestria', 'Maestría')], max_length=20)),
                ('generacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escuelas', to='alumnos.generaciones')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Grupo/Licenciatura')),
                ('mes_graduacion', models.CharField(blank=True, choices=[('enero', 'Enero'), ('febrero', 'Febrero'), ('marzo', 'Marzo'), ('abril', 'Abril'), ('mayo', 'Mayo'), ('junio', 'Junio'), ('julio', 'Julio'), ('agosto', 'Agosto'), ('septiembre', 'Septiembre'), ('octubre', 'Octubre'), ('noviembre', 'Noviembre'), ('diciembre', 'Diciembre')], max_length=20, null=True, verbose_name='Mes de Graduación')),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='alumnos.escuela')),
                ('generacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='alumnos.generaciones')),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Alumno')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('folio_camara', models.CharField(blank=True, max_length=50, null=True, verbose_name='Folio de Cámara')),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='alumnos.escuela')),
                ('generacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='alumnos.generaciones')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='alumnos.grupo')),
            ],
        ),
    ]
